# Generated by Django 4.1 on 2022-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spaces', models.IntegerField()),
                ('time', models.TimeField()),
                ('charging_fees_per_time', models.IntegerField()),
            ],
        ),
    ]
