# Generated by Django 4.1 on 2022-09-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeWayVenues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
