# Generated by Django 4.1 on 2022-09-02 19:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FreeWayVenues', '0002_venue_location_venue_name_venue_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
