# Generated by Django 4.1 on 2022-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FreeWayVenues', '0003_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='customer_care_number',
            field=models.IntegerField(null=True),
        ),
    ]
