# Generated by Django 4.0 on 2022-11-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FreeWayVenues', '0005_remove_venue_charging_fees_per_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBarriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barrier', models.CharField(blank=True, max_length=2, null=True)),
                ('Venue', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='FreeWayVenues.venue')),
            ],
        ),
    ]
