# Generated by Django 4.0 on 2022-11-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FreeWayVenues', '0005_remove_venue_charging_fees_per_time_and_more'),
        ('VenueBarriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuebarriers',
            name='Venue',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='FreeWayVenues.venue'),
        ),
    ]
