# Generated by Django 4.1 on 2022-09-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInstance', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license_plate',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
