# Generated by Django 4.1 on 2022-09-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FreeWayVenues', '0005_remove_venue_charging_fees_per_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges_amount', models.IntegerField()),
                ('venue', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FreeWayVenues.venue')),
            ],
        ),
    ]
